name: CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven
      - name: Package
        run: mvn clean verify
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Bitwise-${{ github.sha }}.AppImage
          path: target/jpackage/*

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven
      - name: Package
        run: mvn clean verify
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Bitwise-${{ github.sha }}-Windows.zip
          path: target/jpackage/*

  macos:
    name: MacOS (Arm)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven
      - name: Package
        run: mvn clean verify -Pmacos
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Bitwise-${{ github.sha }}-MacOS.dmg
          path: target/jpackage/*

  release:
    name: Continuous Release
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - ubuntu
      - windows
      - macos
    steps:
      - uses: actions/checkout@v5
      - name: Download Appimage
        uses: actions/download-artifact@v8
        with:
          name: Bitwise-${{ github.sha }}.AppImage
          path: .
      - name: Download Windows Build
        uses: actions/download-artifact@v8
        with:
          name: Bitwise-${{ github.sha }}-Windows.zip
          path: .
      - name: Download MacOS Build
        uses: actions/download-artifact@v8
        with:
          name: Bitwise-${{ github.sha }}-MacOS.zip
          path: .
      - name: Configure Tag
        run: |
          git tag --force continuous ${{ github.sha }}
          git push --tags --force
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          draft: false
          prerelease: true
          name: Continuous
          tag: continuous
          artifacts: "Bitwise-${{ github.sha }}.AppImage,Bitwise-${{ github.sha }}-Windows.zip,Bitwise-${{ github.sha }}-MacOS.zip"
