name: CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set vars
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven
      - name: Package
        run: mvn clean verify
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: Bitwise-${{ steps.vars.outputs.sha_short }}-Ubuntu
          path: target/jpackage/*

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set vars
        id: vars
        run: echo "sha_short=`echo ${{ github.sha }} | cut -c1-8`" >> $GITHUB_OUTPUT
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven
      - name: Package
        run: mvn clean verify
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: Bitwise-${{ steps.vars.outputs.sha_short }}-Windows
          path: target/jpackage/*

  macos:
    name: MacOS (Arm)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set vars
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven
      - name: Package
        run: mvn clean verify -Pmacos
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: Bitwise-${{ steps.vars.outputs.sha_short }}-MacOS
          path: target/jpackage/*

  release:
    name: Continuous Release
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - ubuntu
      - windows
      - macos
    steps:
      - uses: actions/checkout@v5
      - name: Set vars
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Download appimage
        uses: actions/download-artifact@v8
        with:
          name: Bitwise-${{ steps.vars.outputs.sha_short }}-Ubuntu
          path: .
      - name: Download Windows build
        uses: actions/download-artifact@v8
        with:
          name: Bitwise-${{ steps.vars.outputs.sha_short }}-Windows
          path: .
      - name: Download MacOS build
        uses: actions/download-artifact@v8
        with:
          name: Bitwise-${{ steps.vars.outputs.sha_short }}-MacOS
          path: .
      - name: Configure tag
        run: |
          git tag --force continuous ${{ steps.vars.outputs.sha_short }}
          git push --tags --force
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          draft: false
          prerelease: true
          name: Continuous
          tag: continuous
          artifacts: "Bitwise-${{ steps.vars.outputs.sha_short }}-Ubuntu,Bitwise-${{ steps.vars.outputs.sha_short }}-Windows,Bitwise-${{ steps.vars.outputs.sha_short }}-MacOS"
